<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RestaurantManagementSystem</AssemblyName>
    <RootNamespace>RestaurantManagementSystem</RootNamespace>
    <ApplicationIcon>restaurant.ico</ApplicationIcon>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <!-- SQLite for local database -->
    <PackageReference Include="System.Data.SQLite" Version="1.0.118" />
    <!-- VB Interaction for InputBox -->
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
  </ItemGroup>

</Project>
